# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build on Commit

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

#    runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: gradle :axelframework:clean :axelframework:build
      env:
        ssr_user: ${{ secrets.ssr_username }}
        ssr_password: ${{ secrets.ssr_password }}
        ssr_passphrase: ${{ secrets.ssr_passphrase }}
        github_user: ${{ secrets.username }}
        github_axel_token: ${{ secrets.axel_token }}
        github_token: ${{ secrets.github_token }}
        signing_key: ${{ secrets.signingkey }} 
        signing_keyid: ${{ secrets.signingkeyid }} 
        signing_password: ${{ secrets.signingpassword }} 
      
      
      
