# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish Axel Jar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

#    runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
# try comments
#      run: ./gradlew :axel-common:clean :axel-common:build
      run: gradle :axel-jar:clean :axel-jar:build
      env:
        github_user: ${{ secrets.username }}
        github_axel_token: ${{ secrets.axel_token }}
